### PR TITLE
Replaced toml with go mod

### PR DESCRIPTION
**Pull request by athulmurali**
- Enables continuous support of plugin support in 7.x  
- Building files are simpler now 
- Build with any golang version > 1.14 

How to test this ?

- Go to the GOPATH (find it using `go env`) 
- create a folder src if not present
- clone this into src 
-  Then do the build formalities `go mod vendor  && yarn && ./build.sh`
- copy to the plugins location and make sure grafana version < 8 

Testing the data source
image

Testing the metrics  plugin requests 
image

Simpler package management  :)

### CODE REVIEW

**Comment by athulmurali** [comment]
Once tested versioning can be updated

**Comment by doubleUTF** [comment]
Tested with Go 1.16.6, can run 'go mod vendor' and successfully build package.

**Review by doubleUTF — APPROVED** [review]
LGTM

**Review by doubleUTF — CHANGES_REQUESTED** [review]
Since we're moving to 1.16, in `build.sh` we should replace the string "dependencies not installed try running: dep ensure" with "dependencies not installed try running: go mod vendor"

**Comment by athulmurali** [comment]
@doubleUTF  good catch. Let's do it. 

Also, checking about the legal constraints for nvm and grafana toolkit

**Review by doubleUTF — APPROVED** [review]
New changes look good

**Pull request merged**
