### PR TITLE
Metric label customization changes

### PR DESCRIPTION
**Pull request by huskerdhf**
### Overview
This PR encompasses the following changes to the metrics plugin related to how metrics labels are generated:
- The default behavior when no custom legend format is provided has been changed to:
    - \<Metric Name\>[<Dimension 1 value> | <Dimension 2 value> | ... \<Dimension N value\>]
    - In the latest version of the metrics plugin, the metric label format is similar except the dimension values are comma separated (and thus hard to distinguish) and any dimension values containing an OCI resource OCID are shortened.
    - With this change the full resource OCID will be shown in the default metric label for dimensions containing a resource OCID.
- Metric query editor now includes a *Legend Format* field which if empty will cause the metric plugin to generate the default metric label.
    -  UpdatedMetricsDataPanel-QueryEditor-v2
    - If the *Legend Format* field contains a custom format then the metrics plugin will use this format when generating the label value for each metric.
    - The Legend Format field can contain any printable literal text sequences along with any number of placeholders where the supported placeholders are:
        - {{metric}} - Will be replaced by the metric name 
        - {{dimensionName}} - Will be replaced by the value of the specified dimension
    - For a more detailed explanation of the metric label customization format, see the updated plugin documentation included as part of this PR.
    - When the contents of the Legend Format field in the query editor is changed, the information in the panel is regenerated including the metric labels.

### Example Use of Custom Metric Labels

The following screenshot shows a metrics dashboard with three rows where each row contains two data panels with the exact same query where the left side data panel has no custom legend format and the right side panel does have a defined custom legend format. Each of the rows present a metric from the `oci_computeagent`, `oci_lbaas`, and `oci_objectstorage` metric namespaces respectively.

ExampleMetricDataPanelsUsingCustomLabelFormat

### Testing

The changes on this PR were tested in the following ways:
- Plugin changes were tested Mac and Linux O/Ses.
- A test dashboard was created with data panels using a variety of legend formats to ensure that the plugin generated the appropriate resulting metric label where the following test cases were covered:
    - Default label format (no value provided for Legend Format field) for a variety of OCI resource metrics including one from compute, LBaaS, and object storage metric namespaces.
    - Valid custom label formats
        - Using different combinations of placeholders
        - Using different combinations of placeholders with preceding, intermediary, and trailing literal text
        - Different legend formats for each query within a single data panel
        - Preceding whitespace between opening brace and placeholder name
        - Trailing whitespace between placeholder name and closing brace
        - Preceding and trailing whitespace around placeholder name within braces
        - Different combinations of literal text characters including special characters
    - Invalid custom label formats
        - Placeholders within placeholders, e.g. {[resource{[metric}}DisplayName}}
        - Placeholders with whitespace in the format, e.g. {{resource DisplayName}}
        - Placeholders with the wrong case for one or more characters, e.g. {{resourcedisplayName}}
        - Placeholder referencing non-existent metric dimension name
        - Placeholder with missing opening brace
        - Placeholder with missing closing brace
- The metric query editor and the new Legend Format field were tested within a data panel using the OCI metrics plugin as its datasource as well as in the Grafana Explore window. 

### Documentation

The "using" section of the plugin documentation has been updated to reflect this new functionality as well as a few editorial updates.

### CODE REVIEW

**Comment by mamorett** [comment]
Hi @huskerdhf . I noticed this behaviour with the vnic metric: 
image
Without legend format it displays correctly the vin ocid, still not the Displayname of that specific resources. Other resources works fine:
image

**Comment by huskerdhf** [comment]
> Hi @huskerdhf . I noticed this behaviour with the vnic metric: image Without legend format it displays correctly the vin ocid, still not the Displayname of that specific resources. Other resources works fine: image

The custom legend format for that metric can only be '{resourceId}' (or something similar with additional literal text) since there is only a single dimension of that name associated with the `VnicFromNetworkBytes` metric. Perhaps the documentation should say {<dimension>} or {<dimensionName>} to be clearer.

**Review by mamorett — APPROVED** [review]
Looks good to me.

**Comment by huskerdhf** [comment]
Updated the PR to address two issues:
- Metric label format placeholders should have had two sets of curly braces, e.g. {{resourceDisplayName}}, rather than 1 set of curly braces, e.g. {resourceDisplayName}
    - This led to changes in the documentation and images within the documentation
- I noticed that the UI changes somehow added an extra blank "bar" to the metrics query editor so I fixed the query editor HTML file so that extra blank bar wouldn't be shown.

**Review by nagarnar — APPROVED** [review]

**Pull request merged**
