### PR TITLE
Plugin modification to support enhanced features with Grafana 8

### PR DESCRIPTION
**Pull request by chillaxd**
Features supported:
- Supports Grafana8
- Alerting
- Multi-tenancy data metrics via multi profile or cross tenancy policy
- Filter based on resource tags
- Filter by group by option
- Filters are more user-friendly (show names instead of ocid)
- Dashboard support labels like Prometheus

Signed-off-by: Chiranjit Datta

### CODE REVIEW

**Comment by chillaxd** [comment]
Please don't merge.
It requires review.

**Comment by MaikiGirardi** [comment]
Hi,

Looking for help to validate i'll post some issues that i found on this PR today. Issues that i noted:

1) After i update i've lost some configurations on graphs and then it stopping working. So, when i select the data again that is missed, all the other fields are erased and i should fill all again.

2) I'm monitoring CPU from instance machines and i have a instance pool, so my ecosystem tends to power on and off machines from time to time. When this happen the graph is mixing data from one machine to another instead of being null.
image

3) Fields on Query won't filter data properly:
image
image

If this won't help, please let me know and i stop posting.

**Comment by chillaxd** [comment]
> Hi,
> 
> Looking for help to validate i'll post some issues that i found on this PR today. Issues that i noted:
> 
> 1. After i update i've lost some configurations on graphs and then it stopping working. So, when i select the data again that is missed, all the other fields are erased and i should fill all again.
> 2. I'm monitoring CPU from instance machines and i have a instance pool, so my ecosystem tends to power on and off machines from time to time. When this happen the graph is mixing data from one machine to another instead of being null.
>    image
> 3. Fields on Query won't filter data properly:
>    image
>    image
> 
> If this won't help, please let me know and i stop posting.

I will check and reply you back

**Comment by MaikiGirardi** [comment]
Hey guys, any plans to release this version soon? We are missing alerts and multi tenant support.

**Comment by celtawil** [comment]
any update on the ETA for this to be released ... mostly interested in Alerting being enabled on this datasource

**Comment by YogiTiwari** [comment]
We are trying to configure dashboard based on multiple OCI tenancies We could add two tenancies as OCI data source. One tenancy is on which we have installed Granana and for it we can make the dashboard. However when we try to make the report for other tenancy (where granae is not installed) then we don't get the list of compartments while making the dahsboard. From the instance where we have installed grafana we can make a CLI query to list compartments and metrics of other tenancy so permissions seems to be fine.
Did we miss something or this plugin works only for the single tenancy.

**Pull request closed without merging**
